services:
  frontend-products-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-products-container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    external: true
